### ISSUE TITLE
.gif is not starting from the beginning

### ISSUE THREAD

**Issue by AstralBlader** [a161803398/PlexstormCapture#5]
Like the title says:
The gif isn't starting from the start. It's more like the gif is always playing in the background. 
Could you make it so that the gif reloads and starts from the beginning?

**Comment by AstralBlader** [comment]
add in www/client/donate.js in line 63.5*: `donateImg.src = "";`
and in www/client/subscript.js line  32.5*: `donateImg.src = "";`

* .5 means in between ... basically add that before `donateImg.src = "img/" + ...`

**Comment by a161803398** [comment]
Thank you, I will fix it in next build.
